language: node_js
node_js:
  - "6"
script:
  - npm run test
script:
  - npm run lint
script:
  - npm run flow
branches:
  only:
    # - master
cache:
  directories:
  - $HOME/.npm
after_success:
  - "npm run coveralls"
