export default {
  SELECT_ADD_SET: 'SELECT_ADD_SET',
  SELECT_TOGGLE_OPEN: 'SELECT_TOGGLE_OPEN',
  SELECT_HANDLE_CLICKOUT: 'SELECT_HANDLE_CLICKOUT',
  SELECT_SEARCH_OPTIONS: 'SELECT_SEARCH_OPTIONS',
  SELECT_TAKE_VALUE: 'SELECT_TAKE_VALUE',
  SELECT_CLEAR_ALL: 'SELECT_CLEAR_ALL',
};
