// TODO: Add convenience helper
export default {
  RSM_ADD_SELECT: 'RSM_ADD_SELECT',
  RSM_TOGGLE_OPEN: 'RSM_TOGGLE_OPEN',
  RSM_HANDLE_CLICKOUT: 'RSM_HANDLE_CLICKOUT',
  RSM_SEARCH_OPTIONS: 'RSM_SEARCH_OPTIONS',
  RSM_SAVE_SELECTED: 'RSM_SAVE_SELECTED',
  RSM_REMOVE_SELECT: 'RSM_REMOVE_SELECT',
};
